repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort


  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

# exclude: test/
